### ISSUE TITLE
Bad SMIRNOFF links

### ISSUE THREAD

**Issue by dwhswenson** [openforcefield/openforcefield.org#184]
Related to #114, #121  (etc.)

There are several other places that have the broken link (`topology/smirnoff.html`), the FAQ being one of the more problematic. Here's a search that finds them:

https://github.com/openforcefield/openforcefield.org/search?q=%22topology%2Fsmirnoff%22

Posting as a separate issue because it can fixed without fixing the details of getting a working `stable` docs build discussed in #121.

**Comment by jchodera** [comment]
Thanks for catching this, @dwhswenson!

**Comment by jchodera** [comment]
It appears that this was due to the decision to delete the `topology` branch, which also scrubbed it from the readthedocs page.

We can replace most of these with the RTD link for the latest SMIRNOFF specification should be:
https://open-forcefield-toolkit.readthedocs.io/en/latest/smirnoff.html

However, I think some of those items linked to the draft proposal, which would have been closer to [this version](https://github.com/openforcefield/openforcefield/blob/fd3788669d3e35b4c9f0ff47c420a5010a6c95c6/The-SMIRNOFF-force-field-format.md) which is no longer on readthedocs.

I'll fix these.

**Comment by davidlmobley** [comment]
Have these been fixed, @jchodera ?

**Comment by jchodera** [comment]
Whoops! Fixed here: https://github.com/openforcefield/openforcefield.org/pull/198
