### ISSUE TITLE
Making a "how to cite" page

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield.org#382]
@Yoshanuikabundi and I were talking about how to make it possible for writers to figure out which OpenFF papers/zenodo entries to cite. While Zenodo entries are available for distinct software releases, one challenging case is @ChayaSt's torsion interpolation paper, which isn't tied to a codebase, but is the basis for important results. 

We think that a central "how to cite" page for all of OpenFF would be useful, and it could live on the openforcefield.org website. It could tie in to the current publication yaml system, and contain at least basic instructions like 

(The following links are accurate to the best of Jeff's knowledge on Apr 1 2022)

* How to cite FFs (right now basically everyone should cite the main [Parsley paper,](https://dx.doi.org/https://doi.org/10.1021/acs.jctc.1c00571)), additionally they can use the table in the [openff-forcefields readme](https://github.com/openforcefield/openff-forcefields#open-force-fields) to get the specific FF's DOI.
* How to cite the OpenFF toolkit (Recommend they find their specific version's DOI, but provide the ["auto-latest-version DOI"](https://doi.org/10.5281/zenodo.597754) for lazy folks) and [SMIRNOFF paper](https://dx.doi.org/10.1021/acs.jctc.8b00640)
* How to cite OpenFF Evaluator ([Zenodo DOI](https://doi.org/10.5281/zenodo.3406479)) and [preprint](https://doi.org/10.33774/chemrxiv-2021-jz3zq)
* How to cite things like BespokeFit ([Zenodo DOI](https://zenodo.org/record/5172174), could be updated with publications)
* How to cite special features 
    * "If your work uses Wiberg bond-order based parameter interpolation. please cite [this preprint](https://doi.org/10.1101/2020.08.27.270934)

**Alternatives considered**

We considered having a logging statement in the code that would state which paper to cite, but that seems like it would just add to our overwhelming terminal output, either be untested or add a lot of complexity to test, be hard to extend for further papers, and would confuse the majority of users. 

Another thought is to have each repo's docs contain relevant publications that users should cite, but I don't expect that people would scramble to find all the docs in their conda environments to figure out which dependencies were pulled in and how to cite them. This becomes an especially large maintenance issue if we forget to update individual repos' pages and things become actively wrong.

**Comment by davidlmobley** [comment]
This is probably a good idea. 

Someone in my group also just finished developing code (from something Dave Slochower had done) we could share if it is useful that can take a tag in a Zotero bibliography and automatically push it to a GitHub page/GitHub pages page... so, if, say, we wanted to designate a single individual to make sure every OpenFF-relevant thing gets put onto the website, it could be as simple as them putting it into Zotero and adding a tag to it.

Not sure if this solves any problems we have here, but just offering it in case it is helpful.

**Comment by jchodera** [comment]
This is a really important feature, since citations are one of the primary ways we will justify continued support of this project to the NIH. 

The proposal to provide instructions on how to cite the current toolkit, force fields, and so on in a manner that we will be able to identify via google scholar is a great start. The [landing page for mdtraj](https://www.mdtraj.org/1.9.8.dev0/index.html#citation-doi-for-citing-mdtraj), for example, has an easy copy-and-paste box that makes it very easy to cite the package:
![image](https://user-images.githubusercontent.com/3656088/153724472-745b8c0d-6362-4fb7-8b64-a267c19544e1.png)
This is undoubtedly a driver behind why it now has 970 citations:
![image](https://user-images.githubusercontent.com/3656088/153724489-acf48e6e-dcf0-43f6-851a-b7d765145269.png)

@davidlmobley : I highly recommend we leverage the YAML databases in the GitHub repo instead of a Zotero library maintained by a single individual. The single point of failure sounds very fragile, while everyone generating every kind of research product (software release, paper, force field) can shoulder part of the responsibility for contributing an entry for their product to the YAML files. Spending a bit of effort in making sure our templates for these YAML entries capture everything we need to describe the research output, explain how it aligns with our funding, provide a citable reference, identify contributors, and provide key dates (preprint, publication/release date) will also make it multi-purpose: We can feed these entries into the "how to cite us" page as well as generate most of the material for grant reporting automatically by simply aggregating all research outputs generated within the reporting period.

I would love to see automatic citing schemes like [duecredit](https://github.com/duecredit/duecredit) eventually take off, but the baseline is to just get something that is easy for people to copy-and-paste and make sure we are indexed appropriately in Google Scholar.

**Comment by jameseastwood** [comment]
This page exists and I just updated it, so I am marking this issue completed.
